language: node_js
install: skip

env:
  # 'foobar' (bare)
  - secure: "Qc3GO7R4dafaAsAHSytrBnYEJBD3t5VANCIGqgU1hbNJ1WO+Nk+XZNEKwtq4v4myvjNjtBIZEhzmIdz+XKm/UDzNJnUE5MR/N78ApCRBQ5w3YMeA1c27FJgGxhPewGvRLub+gIJ+Pv9cOQn6+FxN18ND5jHvhSE/2PDGyppU6U4BIljUokKpm3FH643m0wsRQD4ckh54eIYjEUVTIEcHaQn13OeYBtt830t7kb9xav0kZQm8VKhVT583WBur8XdLiXXWsGMfhR4WxE/Xyb7k1dD+7D1ysv5T5X33ZM2y/iqFyOMONn3YHR4QLn4i+augatON83cBKuEpHO1nWRU4r12dXPvDnOyIaeFiZXf/JuD7GO3i0U/YRYXU2mVyqGoSMtdmi/66DxY2gnnM7y44TsEcQuJuLL+XnvkMCZYWsZU0q29G0DEGB3n2VTw7tc3g9e1xHeyrbAsktmLO+wnbKMpI9P5qgbmzf/L83G1LGVRjUrgLsl/EHABkVw6eqwIXo6cXK/mgler48k0pYBuZT2AcxmD02+4ZdGOK3wFQEBYCNbkdnUAufzglXseUBDnGhSXCBE9Jm3qIK7HamZQ11gOXRggLiF/LZJdjTL6aheFO8cEXTyg4Be1MJTXMd5P5iYnTEt9bV2bSvW0muvxGjMTwgKWcy/fTYyoAgXnc5as="
  # 'foo=bar' (env var assignment)
  - secure: "E4CAZi9u4M6c3+EkaNcIRwINTV3Hq0ISNKUOwZxg8Ry5QeSYvHkRU8rAEHAIyp4Uo7/8e5sdrGJN161piiE5TjowbGV0Gm9MCo//1N/jfySTzbKWzyL4o9u7mpGBe4QiD9musZVtT4fmDb64CbGZfFMhLALPydbXJfd0da/WNcaOU+k4WUdRG9DJNOnOHHhO5QX270A8yIm+AuduFWQe+dGG+94dA+ga2AUY/CdMovkbYANI5cyaTFZVdXX5lermkB9BJPbGJPljO4gn292ypZ5D6o/2B0ezWzaolUAUJKR5jaR87679resFMzAXcNLc9w9bGkEa2mIQdMpNiM5oi1pxWQM47U07xrxsrXF3Cjkw3gBwhqe2Y4YILxHueI0rn4gNVNePELC+28nIh9/cxBNFX2rH9zMmmhTMAGLOhcefrs3H0LF6BBV4j7olI8/b5IEgqRzm3JMChlldJvOXNRBBnG/m3i6C4lmYVMZH88z++BwORVcuP6TfaDpTb1GEkvBm60N2mDNoFrCGr9MJaJtKeR8PkJ5YSWF0pjVgT0xyA67YfLQDL8N+Sbtz+S4l8CzDFq652ODbufuVHMp+NER7TAKr6sQPTFW6gXuoJH2EHl32Qan6MGbCFLyUHrV9fov4iWPkWGB8ryEhezbAfCMqcBRRohyZJtU2GYyL2Yk="
script: skip

notifications:
  email: false
  
