language: node_js
install: skip

env:
  # 'foobar' (bare)
  - secure: "EEJE7miivBWSZ1TMS0KmKYyCOgckwL9Mwj3sS9eDUyjZWObXPstuQU0WO7YCOePOoheFH/mx0ZOCVN40ssCGhdNilMz02z5y0peTwCnovWebBsq4IvpzHULSFamkj0Ri1BbGgHl8pd7KfktEoqpow1ls56sNA9rJ8GN0ruEMkKYi1Z1YKNltI7N1h++Gbrx+wuLS92ZmOULccLTtAd8gt85DuBMDxjW71XHGXDOo9GDLDYvrHd9TQDvIgqXRlWf03DLoJFVfhuyHzp44OhcsVahw6IDwe8vlBn5OTY/KE0kAKkNS+XeZtiVw7ozsX+YUNSodlyolHhq6NM9vJfKsCdChoyQ16q9fPYezcZTtN1JLX0THgfkrk+mWUEnFkRCRHHgJS2kw2B3d7R92mubJQjaCke+BarzqeFrGrocetXcIce+FhqA94yb+9nYVEWX+1hqHTkkfxCnhSvTp1uYANr66oOs1pQ+UrrQ7eocoUnfNHVYvT3P0Vu2+zNXp4L8fT085Vf7hEYhSRTslWV74GQiTcFsdpAXGfueIGpHA9dnq7nLk35CO7sljm7WccfPZBrSKigzYP5RJMZtosCmblVg+JKq6PZ6aH3GK8lpSmE0bE8HUlra8KhRLBv5bdybsWteUgr8vJoDYxYnKlL0eZAScu2cvFVS82oEtbV5dm4s="
  # 'foo=bar' (env var assignment)
  - secure: "eE1l++W3YusLJMhg+PpgVvM6W7S/sEBIY/vW9OhRVmQlDG2jJleJ8oqR+S/ky7F++eW4Ob+fMxuYCqYrdkXZWzb9JzU460uFPz4YgzGGfEjvCOJILQ3hLfkeFwQlffLIcYDP3Ni6DOrbA1w3ncBa7XcQSRI4YOqqR079tj+nMs88ku+IzQZi/1ibG7jxrkMA3kNfV1U6alqIdMLkTw7pN5hVq3Bc06cmNxV2iScFouT7l3PXEvbMgIJ74ZgSpqnZcp1vQZOpoSOfC2b6IMwH5OQ9/E4uxAUOvMuODgMp7AbwjoeoErut4REfvkViSNrnH6lYin1qhE+ylGWsMsG37bS9N4zr30cLn1n9mPghCCyq7gVlKBIq7DwQ0bhQTh90NTG+bubYYZdEkbcW5neZJnEVH494r6eNQ4QTGuPZporUNAztDM94hucdG93YB2gckRJXIckPL6sFfM8LXWt77F2WzHq7DNWloj8uZuatBRrn9hHPw9B4QOkjDJG2J8VHz6Qu2c6/t9DFBUvE9tuLBXEI2PfxFUyLFAezc/03IvUD8LIfZ2vxE/f3FC5CpNmWL2dVnFgt0uvE/LwjSaD+/FnT+1+CJXypKfulWPAf8JtHevFd9Jscpe210gYKUbzOvk9hDqajeeuhrNGCt/Ys0x4gzsyI1fSx3svJ+Tg2no4="

script: skip

notifications:
  email: false
